# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/springdemo?serverTimezone=UTC
    username: root
    password: root
  application:
    name: collectionsys
# 应用服务 WEB 访问端口
server:
  port: 8080
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations : classpath:mappers/*xml


